/**
 *  Product List
 */

export default [
  {
    id: 0,
    artNo: "1000-0047",
    name: "Fan Scarf Marathon",
    slug: "1a",
    pictures: [
      "../../public/assets/images/scarves/fan-scarf-marathon.jpg",
      "../../public/assets/images/scarves/fan-scarf-marathon.jpg",
    ],
    stock: 32,
    //price: 3500,
    // "discount": 1000,
    salePrice: 2500,
    description:
      "Get your marathon scarf from Wildemasche. Custom knitted with your design and text. Create your runners scarf online. Your favourite text, logo or personal message in a scarf",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Marathon"],
  },
  {
    id: 1,
    artNo: "1000-0048",
    name: "Football Scarf Blue White",
    slug: "2b",
    pictures: [
      "../../public/assets/images/scarves/football-scarf-blue-white.jpg",
      "../../public/assets/images/scarves/football-scarf-blue-white.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in blue and white. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Scarves"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Blue & White"],
  },
  {
    id: 2,
    artNo: "1000-0049",
    name: "Football Scarf Darts",
    slug: "3c",
    pictures: [
      "../../public/assets/images/scarves/football-scarf-darts.jpg",
      "../../public/assets/images/scarves/football-scarf-darts.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "The bundesliga is the major football / soccer league in Germany. Design your football scarf with custom design, made to order with you team name and logo.",
    rating: 5,
    tags: ["Scarves"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Red"],
  },
  {
    id: 3,
    artNo: "1000-0050",
    name: "Football Scarf Leather",
    slug: "4d",
    pictures: [
      "../../public/assets/images/scarves/football-scarf-leather.jpg",
      "../../public/assets/images/scarves/football-scarf-leather.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "The first football you can wear around your neck. Customize and order online now.",
    rating: 5,
    tags: ["Scarves"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Leather"],
  },
  {
    id: 4,
    artNo: "1000-0051",
    name: "Football Scarf Europe",
    slug: "5e",
    pictures: [
      "../../public/assets/images/scarves/football-scarf-europe.jpg",
      "../../public/assets/images/scarves/football-scarf-europe.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Custom football for the old world: Europe is calling, the blue background with the yellow stars of the founding members of the European Union. No minimum order required, scarf is knitted from one single piece with custom design.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Europe"],
  },
  {
    id: 5,
    artNo: "1000-0052",
    name: "Football Scarf Christmas",
    slug: "6f",
    pictures: [
      "../../public/assets/images/scarves/football-scarf-christmas.jpg",
      "../../public/assets/images/scarves/football-scarf-christmas.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Custom football christmas scarf santa would be proud of: the perfect gift for fans. Just add your FC, united or city logo, and off you go in christmas or team colors. Woolen soccer scarves to warm your neck in winter, as birthday gift or present for fellow supporters. Have yours personalized and knitted today.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Christmas"],
  },

  {
    id: 6,
    artNo: "1000-0055",
    name: "Football Scarf Red Black",
    slug: "9i",
    pictures: [
      "../../public/assets/images/scarves/football-scarf-red-black.jpg",
      "../../public/assets/images/scarves/football-scarf-red-black.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in red and black. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Red & Black"],
  },
  {
    id: 7,
    artNo: "1000-0056",
    slug: "10j",
    name: "Football Scarf White Blue",
    pictures: [
      "../../public/assets/images/scarves/football-scarf-white-blue.jpg",
      "../../public/assets/images/scarves/football-scarf-white-blue.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in blue and white. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["White & Blue"],
  },
  {
    id: 8,
    artNo: "1000-0057",
    name: "Football Scarf Dark Blue White",
    slug: "11k",
    pictures: [
      "../../public/assets/images/scarves/footall-scarf-white-dark-blue.jpg",
      "../../public/assets/images/scarves/footall-scarf-white-dark-blue.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in dark blue and white. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Dark Blue & White"],
  },
  {
    id: 9,
    artNo: "1000-0058",
    name: "Football Scarf Yellow Red",
    slug: "12l",
    pictures: [
      "../../public/assets/images/scarves/football-scarf-yellow-red.jpg",
      "../../public/assets/images/scarves/football-scarf-yellow-red.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in yellow and red. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Yellow & Red"],
  },
  {
    id: 10,
    artNo: "1000-0053",
    name: "Football Scarf Black White",
    slug: "7g",
    pictures: [
      "../../public/assets/images/scarves/football-scarf-white-black.jpg",
      "../../public/assets/images/scarves/football-scarf-white-black.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in black and white. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Black & White"],
  },
  {
    id: 11,
    artNo: "1000-0054",
    name: "Football Scarf Blue Yellow",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/football-scarf-blue-yellow.jpg",
      "../../public/assets/images/scarves/football-scarf-blue-yellow.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in blue and yellow. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Blue & Yellow"],
  },
  {
    id: 12,
    artNo: "1000-0055",
    name: "Football Scarf Black Amber",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/Black-Amber.jpg",
      "../../public/assets/images/scarves/Back-Amber.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in Black Amber. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Black & Amber"],
  },

  ,
  {
    id: 13,
    artNo: "1000-0056",
    name: "Football Scarf Black Red",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/Black-Red.jpg",
      "../../public/assets/images/scarves/Black-Red.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in Black Red. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Black Red"],
  },
  ,
  {
    id: 14,
    artNo: "1000-0057",
    name: "Football Scarf Black White",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/Black-White.jpg",
      "../../public/assets/images/scarves/Black-White.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in Black White. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Black & White"],
  },
  ,
  {
    id: 15,
    artNo: "1000-0058",
    name: "Football Scarf Black Yellow",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/Black-Yellow.jpg",
      "../../public/assets/images/scarves/Black-Yellow.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in Black Yellow. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Black & Yellow"],
  },
  ,
  {
    id: 16,
    artNo: "1000-0059",
    name: "Football Scarf Green White",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/Green-White.jpg",
      "../../public/assets/images/scarves/Green-White.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in Green White. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Green & White"],
  },
  ,
  {
    id: 17,
    artNo: "1000-0060",
    name: "Football Scarf Navy Sky",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/Navy-Sky.jpg",
      "../../public/assets/images/scarves/Navy-Sky.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in Navy Sky. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Navy & Sky"],
  },
  ,
  {
    id: 18,
    artNo: "1000-0061",
    name: "Football Scarf Navy White",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/Navy-White.jpg",
      "../../public/assets/images/scarves/Navy-White.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in Navy White. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Navy & White"],
  },
  ,
  {
    id: 19,
    artNo: "1000-0062",
    name: "Football Scarf Navy Yellow",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/Navy-Yellow.jpg",
      "../../public/assets/images/scarves/Navy-Yellow.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in Navy Yellow. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Navy & Yellow"],
  },
  ,
  {
    id: 20,
    artNo: "1000-0063",
    name: "Football Scarf Red White",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/Red-White.jpg",
      "../../public/assets/images/scarves/Red-White.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in Red White. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Red & White"],
  },
  ,
  {
    id: 21,
    artNo: "1000-0064",
    name: "Football Scarf Royal White",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/Royal-White.jpg",
      "../../public/assets/images/scarves/Royal-White.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in Royal White. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Royal & White"],
  },
  ,
  {
    id: 22,
    artNo: "1000-0065",
    name: "Football Scarf Royal Yellow",
    slug: "8h",
    pictures: [
      "../../public/assets/images/scarves/Royal-Yellow.jpg",
      "../../public/assets/images/scarves/Royal-Yellow.jpg",
    ],
    stock: 32,
    //price: 3500,
    discount: 1000,
    salePrice: 2500,
    description:
      "Football scarf with half/half design. The custom scarf for your team in Royal Yellow. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
    rating: 5,
    tags: ["Women"],
    size: ["M", "XL"],
    category: "Scarves",
    colors: ["Royal & Yellow"],
  },
];
